"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[aliases]
check = ["util", "exec", "--", "jj-pre-push", "--checker=prek", "check"]
clone = ["git", "clone", "--colocate"]
closest = ["util", "exec", "--", "sh", "-c", """
jj log --no-graph -r 'closest_bookmark(@)' -T 'stringify(local_bookmarks.map(|b| b.name()).join("\n")).first_line()++"\n"'
""", ""]
fetch = ["git", "fetch"]
push = ["util", "exec", "--", "jj-pre-push", "--checker=prek", "push"]

[experimental-advance-branches]
enabled-branches = ["glob:*"]
disabled-branches = ["exact:main", "exact:master"]

[git]
private-commits = "description(glob:'wip*')"
write-change-id-header = true

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_pushable(to)' = 'heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))'

[revsets]
bookmark-advance-to = 'closest_pushable(@)'

[ui]
conflict-marker-style = "git"
default-command = "log"
diff-formatter = ":git"
pager = ["delta", "--side-by-side"]

[[--scope]]
--when.commands = ["diff", "show"]
[--scope.ui]
pager = ["diffnav", "--side-by-side"]
