"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[aliases]
check = ["util", "exec", "--", "uvx", "jj-pre-push", "check"]
closest = ["util", "exec", "--", "sh", "-c", """
jj log --no-graph -r 'closest_bookmark(@)' -T 'stringify(local_bookmarks.map(|b| b.name()).join("\n")).first_line()++"\n"'
""", ""]
fetch = ["git", "fetch"]
push = ["util", "exec", "--", "uvx", "jj-pre-push", "push"]
tug = ["util", "exec", "--", "sh", "-e", "-c", """
if [ "x$1" = "x" ]; then
  jj bookmark move --from "closest_bookmark(@)" --to "closest_pushable(@)"
else
  jj bookmark move --to "closest_pushable(@)" "$@"
fi
if [ -d .git ]; then git switch $(jj closest); fi
""", ""]

[experimental-advance-branches]
enabled-branches = ["glob:*"]
disabled-branches = ["exact:main", "exact:master"]

[git]
private-commits = "description(glob:'wip*')"
push-new-bookmarks = true
write-change-id-header = true

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_pushable(to)' = 'heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))'

[ui]
conflict-marker-style = "git"
default-command = "log"
diff-formatter = ":git"
pager = ["delta", "--side-by-side"]
